Very minor language-washing in documentation
CPS-IT/project-builder pull request #9
Opened 2022-06-27 12:00 UTC by mteu

2022-06-27 18:54 UTC, mteu commented on docs/architecture.md
> +* Each project type is described by a [**template configuration**](#Configuration) file
Thanks for spotting that. I was gonna align the anchors with the actual headings to get rid of my IDE notices. Eventually, I came to the conclusion that my approach was selfish madness and had next to zero value to the project so I rolled back my pedantic changes. Apparently, I missed one spot. Please accept my apologies. You may omit that anchor. It has no further purpose.

2022-06-27 19:02 UTC, eliashaeussler commented on docs/architecture.md
> +* Each project type is described by a [**template configuration**](#Configuration) file
```suggestion
* Each project type is described by a [**template configuration**](#configuration) file
```

Already, then let's just change it back to the original value and we're fine :)

2022-06-27 19:04 UTC, eliashaeussler requested changes

2022-06-27 19:04 UTC, eliashaeussler commented on README.md
> +a new project in  seconds.
```suggestion
a new project in seconds.
```

2022-06-28 10:33 UTC, eliashaeussler approved these changes

2022-06-28 10:34 UTC, merged